export const selectedFields = [
  'username',
  'email',
  'avatar',
  'bio',
  'roles',
  'followers',
  'following',
  'dob',
  'cover_avatar',
  'location',
  'website',
  'gender',
  '_id',
  'createdAt',
  'status',
  'banReason',
  'suspendedUntil',
  'suspensionReason',
  'warnings',
  'googleId',
  'statusHistory',
].join(' ');
